package com.cook.kotlin.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cook.kotlin.db.model.RecentComic;

import com.cook.kotlin.db.RecentComicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentComicDaoConfig;

    private final RecentComicDao recentComicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentComicDaoConfig = daoConfigMap.get(RecentComicDao.class).clone();
        recentComicDaoConfig.initIdentityScope(type);

        recentComicDao = new RecentComicDao(recentComicDaoConfig, this);

        registerDao(RecentComic.class, recentComicDao);
    }
    
    public void clear() {
        recentComicDaoConfig.clearIdentityScope();
    }

    public RecentComicDao getRecentComicDao() {
        return recentComicDao;
    }

}
